### ISSUE TITLE
crash when 'calculate' (cura 15.06, 15.06 branch)

### ISSUE THREAD

**Issue by ThomasChiroux** [nallath/PrintCostCalculator#5]
Hi,
On Cura 15.06 and PrintCostCalculator from 15.06 branch, when clickling on 'calculate', it crash cura with the following trace:
(my system: archlinux, cura 15.06 compiled from AUR)

```

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/UM/Qt/Bindings/ExtensionModel.py", line 45, in subMenuTriggered
    item["extension"].activateMenuItem(option_name)
  File "/usr/lib/python3.5/site-packages/UM/Extension.py", line 34, in activateMenuItem
    self._menu_function_dict[name]() 
  File "/usr/lib/cura/plugins/PrintCostCalculator.py", line 97, in showPopup
    self._createCostView()
  File "/usr/lib/cura/plugins/PrintCostCalculator.py", line 88, in _createCostView
    path = QUrl.fromLocalFile(os.path.join(PluginRegistry.getInstance().getPluginPath("PrintCostCalculator"), "PrintCostCalculator.qml"))
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

```

**Comment by ThomasChiroux** [comment]
Sorry, bad report, the plugin was in the wrong place..
working fine now.
